[package]
name = "rust_quickjs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.177"
thiserror = "2.0.17"

[[bin]]
name = "qjs"
path = "bin/qjs.rs"

[[bin]]
name = "rust_qjs"
path = "bin/rust_qjs.rs"
